#spring:
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/ghappier/microservice
#          search-paths: config-repo
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\EclipseWorkspaces\SpringCloud\microservice\config-repo #Windows用file:///开头，Linux用file://开头

server:
  port: 6001
